---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: docker
    tag: 'latest'

inputs:
- name: source-code
- name: app-image
- name: version

run:
  path: source-code/ci/scripts/deploy.sh

params:
  APP:
  NAMESPACE:
  PORT:
  ENVIRONMENT:
  SWARM_HOST:
  SWARM_SSH_PRIVATE: