---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 'alpine'

inputs:
- name: source-code

outputs:
- name: build-dir

run:
  path: source-code/ci/scripts/build.sh

params:
